//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_Corse
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Last_Course_WorkEntities : DbContext
    {
        public Last_Course_WorkEntities()
            : base("name=Last_Course_WorkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<відслідкування_оплати_товару_покупцям_або_виплата_товару_посчальнику> відслідкування_оплати_товару_покупцям_або_виплата_товару_посчальнику { get; set; }
        public virtual DbSet<додаткова_інформація_про_товар> додаткова_інформація_про_товар { get; set; }
        public virtual DbSet<замовлення_особи_товару> замовлення_особи_товару { get; set; }
        public virtual DbSet<система_повинна_зберігати_інформацію_про_юзера> система_повинна_зберігати_інформацію_про_юзера { get; set; }
        public virtual DbSet<Товар> Товар { get; set; }
    }
}
