//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_Corse
{
    using System;
    using System.Collections.Generic;
    
    public partial class відслідкування_оплати_товару_покупцям_або_виплата_товару_посчальнику
    {
        public int info_user_id { get; set; }
        public int product_id { get; set; }
        public Nullable<System.DateTime> дата { get; set; }
        public Nullable<double> сума { get; set; }
        public Nullable<int> id { get; set; }
        public string UCR { get; set; }
        public Nullable<System.DateTime> DCR { get; set; }
        public string ULC { get; set; }
        public Nullable<System.DateTime> DLC { get; set; }
    
        public virtual система_повинна_зберігати_інформацію_про_юзера система_повинна_зберігати_інформацію_про_юзера { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
