//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_Corse
{
    using System;
    using System.Collections.Generic;
    
    public partial class замовлення_особи_товару
    {
        public int new_info_product_id { get; set; }
        public int info_user_id { get; set; }
        public Nullable<int> кількість_товару { get; set; }
        public Nullable<System.DateTime> дата { get; set; }
        public int id { get; set; }
        public string UCR { get; set; }
        public Nullable<System.DateTime> DCR { get; set; }
        public string ULC { get; set; }
        public Nullable<System.DateTime> DLC { get; set; }
    
        public virtual додаткова_інформація_про_товар додаткова_інформація_про_товар { get; set; }
        public virtual система_повинна_зберігати_інформацію_про_юзера система_повинна_зберігати_інформацію_про_юзера { get; set; }
    }
}
