//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_Corse
{
    using System;
    using System.Collections.Generic;
    
    public partial class система_повинна_зберігати_інформацію_про_юзера
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public система_повинна_зберігати_інформацію_про_юзера()
        {
            this.відслідкування_оплати_товару_покупцям_або_виплата_товару_посчальнику = new HashSet<відслідкування_оплати_товару_покупцям_або_виплата_товару_посчальнику>();
            this.замовлення_особи_товару = new HashSet<замовлення_особи_товару>();
        }
    
        public string ім_я { get; set; }
        public Nullable<int> код { get; set; }
        public string адреса { get; set; }
        public string категорія_особи { get; set; }
        public Nullable<double> знижка { get; set; }
        public Nullable<double> борг { get; set; }
        public Nullable<double> рахунок_за_місяць { get; set; }
        public int id { get; set; }
        public string UCR { get; set; }
        public Nullable<System.DateTime> DCR { get; set; }
        public string ULC { get; set; }
        public Nullable<System.DateTime> DLC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<відслідкування_оплати_товару_покупцям_або_виплата_товару_посчальнику> відслідкування_оплати_товару_покупцям_або_виплата_товару_посчальнику { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<замовлення_особи_товару> замовлення_особи_товару { get; set; }
    }
}
